set nocompatible               " be iMproved
filetype off                   " required!

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
" required! 
Bundle 'gmarik/vundle'

" My Bundles here:
"
" original repos on github
Bundle 'majutsushi/tagbar'
Bundle 'altercation/vim-colors-solarized'

" Github repos of the user 'vim-scripts'
" => can omit the username part
Bundle 'L9'
Bundle 'FuzzyFinder'

" non github repos
Bundle 'git://git.wincent.com/command-t.git'
" ...
filetype plugin indent on     " required!

"show relative line numbers
set number
set relativenumber
set numberwidth=5
set smarttab "tabs at start, spaces else
set shiftround "indents to nearest tabstop

"spaces...
set ts=2 sts=2 sw=2 expandtab
"but tabs are better =)
"set ts=2 sts=2 sw=2 noexpandtab

"yup
set smartindent

"show whitespace chars and set syntax
set list listchars=tab:»›,trail:·
colo nofrils-dark
set t_Co=256
if !exists("g:syntax_on")
	syntax enable
endif
"allow buffer switch w/o saving
set hidden

"change default split direction
set splitbelow
set splitright

"test autocomplete
"map <Tab> <C-P>

source ~/.vim/startup/mappings.vim
