
"set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
"set runtime to include fzf fuzzy finder
set rtp+=~/.fzf
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
" call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-repeat'
Plugin 'tpope/vim-surround'
" Plugin 'ctrlpvim/ctrlp.vim'
" plugin from http://vim-scripts.org/vim/scripts.html
Plugin 'Smart-Tabs'
Plugin 'matchit.zip'
Plugin 'ruby-matchit'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just
" :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!`
"                   - to auto-approve removal      
"
" see :h vundle for more details or wiki for FAQ

"always show status bar
set laststatus=2
set incsearch "highlight search results
set showmatch "shows matching brace on completion
set matchtime=3 "speeds up showing matching brace
set showcmd "show incomplete commands
set scrolloff=5 "keep 5 lines between edge of editor and cursor

"set cul "highlight current line
set ruler "show cursor coords in status bar
"show relative line numbers and set number column width
set number
set relativenumber
set numberwidth=5

set smarttab "tabs at start, spaces else
set shiftround "indents to nearest tabstop
set autoindent
set list listchars=tab:\|\ ,trail:·,nbsp:·

"spaces...
"set ts=2 sts=2 sw=2 expandtab
"but tabs are better =)
set ts=2 sts=2 sw=2 noexpandtab

"tpope
set backspace=indent,eol,start
set complete-=i

" color schemes can do bright w/o bold
if &t_Co == 8 && $TERM !~# '^linux\|^Eterm'
		set t_Co=16
	endif
"show whitespace chars and set syntax
set t_Co=256
colo nofrils-dark
if !exists("g:syntax_on")
	syntax enable
endif
"allow buffer switch w/o saving
set hidden

"change default split direction
set splitbelow
set splitright

"improve completion in command mode
set wildmode=list:longest,list:full
" set case insensitive search

"improved % matching
if !exists('g:loaded_matchit') && findfile('plugin/matchit.vim', &rtp) ==# ''
	runtime! macros/matchit.vim
endif

"stop at 80 char
set nowrap
set textwidth=80
set colorcolumn=+1


source ~/.vim/startup/mappings.vim
" source ~/.vim/startup/vim_to_tmux.vim
