# prompt and async
export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh

# A list of all directories in which to look for commands,
# scripts and programs
PATH="$HOME/.rbenv/bin:$PATH"                              # RBENV
PATH="/usr/local/share/npm/bin:$PATH"                      # NPM
PATH="/usr/local/bin:/usr/local/sbin:$PATH"                # Homebrew
PATH="/Users/nyxnaut/.rbenv/versions/2.2.3/bin:$PATH"

export EDITOR=nvim
alias chrome='open -a "Google Chrome"'
alias canary='open -a "Google Chrome Canary"'

alias -- -="cd -"
alias ..="cd .."
alias ...="cd ../../"
alias ....="cd ../../../"
alias .....="cd ../../../../"
alias ......="cd ../../../../"
alias ';q'="exit"

alias zshrc='$EDITOR ~/.zshrc && source ~/.zshrc'
alias vimrc='$EDITOR ~/.vimrc'
alias nvimrc='$EDITOR ~/.config/nvim/init.vim'
alias tmuxrc='$EDITOR ~/.tmux.conf'

alias l="ls -la"
alias l="ls -la"
alias ld="ls -ld */"
alias v="nvim"
alias tree="tree -A"
alias treed="tree -d"
alias tree1="tree -d -L 1"
alias tree2="tree -d -L 2"

# Lock the screen (when going AFK)
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"
# Get macOS Software Updates, and update installed Ruby gems, Homebrew, npm, and
# their installed packages

alias update='sudo softwareupdate -i -a; brew update; brew upgrade --all; brew cleanup; npm install npm -g; npm update -g; sudo gem update --system; sudo gem update; sudo gem cleanup'

if ! zplug check; then
  zplug install
fi

# Initialization for FDK command line tools.Mon Sep 12 03:06:33 2016
FDK_EXE="/Users/nyxnaut/bin/FDK/Tools/osx"
PATH=${PATH}:"/Users/nyxnaut/bin/FDK/Tools/osx"
export PATH
export FDK_EXE

# Pure prompt and necessary code
zplug "mafredri/zsh-async"
zplug "sindresorhus/pure"
autoload -U promptinit; promptinit
prompt pure

# Core
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-history-substring-search"

# omz tools
zplug "plugins/git",   from:oh-my-zsh
zplug "plugins/bower",   from:oh-my-zsh
zplug "plugins/brew",   from:oh-my-zsh
zplug "plugins/bundler",   from:oh-my-zsh
zplug "plugins/gem",   from:oh-my-zsh
zplug "plugins/git",   from:oh-my-zsh
zplug "plugins/gitfast",   from:oh-my-zsh
zplug "plugins/rails",   from:oh-my-zsh
zplug "plugins/tmux",   from:oh-my-zsh
zplug "plugins/vi-mode",   from:oh-my-zsh

# Plugin tells you when you forgot an alias
zplug "djui/alias-tips"

# Fuzzy finder
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Load syntax highlighting, keep at bottom of .zshrc
zplug "zsh-users/zsh-syntax-highlighting", nice:10

# Check for and install missing plugs
if ! zplug check; then
  printf "Install [y/n]: "
  if read -q; then
    echo; zplug install
  fi
fi

zplug load --verbose
