# If vim cannot file complete remove zcompdump from zplug directory
# prompt and async
export ZPLUG_HOME=~/.zplug
source $ZPLUG_HOME/init.zsh
source ~/.profile

if ! zplug check; then
  zplug install
fi

# As part of a one-stop-shop update command please do the following:
# apt-get, zplug, nvim plug => upg/upd
# cd ~/.rbenv && git pull
# cd ~/.rbenv/plugins/ruby-build/ && git pull
# pip2 install --upgrade neovim
# pip3 install --upgrade neovim


# Pure prompt and necessary code
# Ugh get the stupid prompt load error again, but still works for now so #lazy
zplug "mafredri/zsh-async", defer:0
zplug "sindresorhus/pure", use:pure.zsh

autoload -U promptinit && promptinit
prompt pure &>/dev/null

# Core
zplug "zsh-users/zsh-completions"

#zplug "plugins/bundler",   from:oh-my-zsh
#zplug "plugins/gem",   from:oh-my-zsh
zplug "plugins/gitfast",   from:oh-my-zsh
zplug "plugins/rails",   from:oh-my-zsh
#zplug "plugins/tmux",   from:oh-my-zsh
zplug "plugins/vi-mode",   from:oh-my-zsh

# Plugin tells you when you forgot an alias
zplug "djui/alias-tips"

# Fuzzy finder
# export FZF_DEFAULT_COMMAND='ag -g""'
# [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Load syntax highlighting, keep at bottom of .zshrc
zplug "zsh-users/zsh-syntax-highlighting", defer:2

# Github page specifically asks for placement after zsh-syntax-highlighting
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
zplug "zsh-users/zsh-history-substring-search", defer:2

# Check for and install missing plugs
if ! zplug check; then
  printf "Install [y/n]: "
  if read -q; then
    echo; zplug install
  fi
fi

zplug load
# eval "$(rbenv init -)"
